### ISSUE TITLE
Photos only?

### ISSUE THREAD

**Issue by ghost** [pascalartho/ch.mycloud.python-download#1]
Hi there!
Was looking for a way to use mycloud from Linux, shame there's no support at all.
Will this only sync photo albums, or can I download/upload (with your other script) from an folder I may have under "Files"?

Thanks!

**Comment by pascalartho** [comment]
Hi usharf,

Thank you for your message.
The example configuration downloads only the "photos" albums, see https://github.com/pascalartho/ch.mycloud.python-download/blob/master/config.ini#L4.
If you want to download a folder you have under "files", use the prefix "/Drive/" in the configuration, compare https://github.com/pascalartho/ch.mycloud.python-upload/blob/master/config.ini#L4.

**In short**

mycloud.ch Prefix | Description
------------------ | -----------
/Drive/|Down- / Upload files under "Files"
/Photos/|Down- / Upload files under "Photos"

Hope this helps,
Pascal

**Comment by ghost** [comment]
Thanks so much. Will try it shortly.
